# Generated by Django 4.2.4 on 2023-08-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_prettynum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prettynum',
            old_name='mobil',
            new_name='mobile',
        ),
    ]
